// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ec73480837208d4d0f1b72d8f49ba4adf90e84d9f7780eea74f11438b3624994
package c2d2s

var (
	C2D2S_P10      = [23]float64{1.0, 1.0e1, 1.0e2, 1.0e3, 1.0e4, 1.0e5, 1.0e6, 1.0e7, 1.0e8, 1.0e9, 1.0e10, 1.0e11, 1.0e12, 1.0e13, 1.0e14, 1.0e15, 1.0e16, 1.0e17, 1.0e18, 1.0e19, 1.0e20, 1.0e21, 1.0e22}
	C2D2S_P10N     = [23]float64{1.0, 1.0e-1, 1.0e-2, 1.0e-3, 1.0e-4, 1.0e-5, 1.0e-6, 1.0e-7, 1.0e-8, 1.0e-9, 1.0e-10, 1.0e-11, 1.0e-12, 1.0e-13, 1.0e-14, 1.0e-15, 1.0e-16, 1.0e-17, 1.0e-18, 1.0e-19, 1.0e-20, 1.0e-21, 1.0e-22}
	__str_d5b592c0 = []byte("NaN")
	__str_c64ddf11 = []byte("-Infinity")
	__str_d0067cad = []byte("Infinity")
	__str_5feceb66 = []byte("0")
)

func emit_lit(dst []byte, s []byte, n uint32) uint32 {
	copy(dst[:n], s[:n])
	dst[n] = 0
	return n
}

func emit_uint_rev(dst []byte, v uint64) uint32 {
	var v3 uint32
	var v5 uint32
	var v2 [24]byte
	v3 = 0
	if v == 0 {
		dst[0] = '0'
		dst[1] = 0
		return 1
	}
	for v > 0 {
		v2[v3] = byte(uint64(48) + (v % uint64(10)))
		v3++
		v = v / 10
	}
	for v5 = 0; v5 < v3; v5++ {
		dst[v5] = v2[int((v3-1)-v5)]
	}
	dst[v3] = 0
	return v3
}

func emit_exp(dst []byte, pos uint32, ev int) uint32 {
	var v3 int
	dst[pos] = 'e'
	pos++
	if ev >= 0 {
		dst[pos] = 43
		pos++
		v3 = ev
	} else {
		dst[pos] = 45
		pos++
		v3 = -ev
	}
	if v3 >= 100 {
		dst[pos] = byte(48 + (v3 / 100))
		pos++
		v3 = v3 % 100
		dst[pos] = byte(48 + (v3 / 10))
		pos++
		dst[pos] = byte(48 + (v3 % 10))
		pos++
	} else {
		if v3 >= 10 {
			dst[pos] = byte(48 + (v3 / 10))
			pos++
			dst[pos] = byte(48 + (v3 % 10))
			pos++
		} else {
			dst[pos] = byte(48 + v3)
			pos++
		}
	}
	dst[pos] = 0
	return pos
}

func floor_log10_pos(m float64) int {
	var v1 int
	var v47 bool
	var v56 bool
	var v65 bool
	var v74 bool
	v1 = 0
	for m >= float64(1e+22) {
		m *= float64(1e-22)
		v1 += 22
	}
	for {
		v12 := (m > float64(0)) && (m < float64(1e-22))
		if !v12 {
			break
		}
		m *= float64(1e+22)
		v1 -= 22
	}
	if m >= float64(1) {
		for m >= float64(1e+16) {
			v1 += 16
			m *= float64(1e-16)
		}
		for m >= float64(1e+08) {
			v1 += 8
			m *= float64(1e-08)
		}
		for m >= float64(10000) {
			v1 += 4
			m *= float64(0.0001)
		}
		for m >= float64(100) {
			v1 += 2
			m *= float64(0.01)
		}
		for m >= float64(10) {
			v1++
			m *= float64(0.1)
		}
	} else {
		for {
			v47 = (m > float64(0)) && (m < float64(1e-08))
			if !v47 {
				break
			}
			v1 -= 8
			m *= float64(1e+08)
		}
		for {
			v56 = (m > float64(0)) && (m < float64(0.0001))
			if !v56 {
				break
			}
			v1 -= 4
			m *= 10000
		}
		for {
			v65 = (m > float64(0)) && (m < float64(0.01))
			if !v65 {
				break
			}
			v1 -= 2
			m *= 100
		}
		for {
			v74 = (m > float64(0)) && (m < float64(0.1))
			if !v74 {
				break
			}
			v1--
			m *= 10
		}
		if m < float64(1) {
			v1--
		}
	}
	return v1
}

func emit_ecma(dst []byte, neg int, s uint64, k int, n int) uint32 {
	var v7 uint32
	var v8 uint32
	var v9 uint32
	var v10 uint32
	var v23 bool
	var v35 bool
	var v46 bool
	var v66 bool
	var v80 bool
	var v97 uint32
	var v5 [24]byte
	v7 = 0
	v9 = emit_uint_rev(v5[:], s)
	v10 = v7
	if n > 0 {
		v10 = uint32(n)
	}
	if neg != 0 {
		dst[v7] = 45
		v7++
	}
	v23 = (k <= n) && (n <= 21)
	if v23 {
		for v8 = 0; v8 < v9; v8++ {
			dst[v7] = v5[v8]
			v7++
		}
		v8 = 0
		for {
			v35 = (n > k) && (v8 < uint32(n-k))
			if !v35 {
				break
			}
			dst[v7] = '0'
			v7++
			v8++
		}
		dst[v7] = 0
		return v7
	}
	v46 = (0 < n) && (n <= 21)
	if v46 {
		for v8 = 0; v8 < v10; v8++ {
			dst[v7] = v5[v8]
			v7++
		}
		dst[v7] = 46
		v7++
		for v8 = v10; v8 < v9; v8++ {
			dst[v7] = v5[v8]
			v7++
		}
		dst[v7] = 0
		return v7
	}
	v66 = (-6 < n) && (n <= 0)
	if v66 {
		dst[v7] = '0'
		v7++
		dst[v7] = 46
		v7++
		v8 = 0
		for {
			v80 = (n < 0) && (v8 < uint32(-n))
			if !v80 {
				break
			}
			dst[v7] = '0'
			v7++
			v8++
		}
		for v8 = 0; v8 < v9; v8++ {
			dst[v7] = v5[v8]
			v7++
		}
		dst[v7] = 0
		return v7
	}
	dst[v7] = v5[0]
	v7++
	v97 = 1
	for v8 = 0; v8 < v9; v8++ {
		if v5[v8] != '0' {
			v97 = v8 + 1
		}
	}
	v9 = v97
	if v9 > 1 {
		dst[v7] = 46
		v7++
		for v8 = 1; v8 < v9; v8++ {
			dst[v7] = v5[v8]
			v7++
		}
	}
	return uint32(emit_exp(dst[:], v7, (n - 1)))
}

func u128_div10_hi(hi uint64, lo uint64) uint64 {
	return uint64(hi / 10)
}

func u128_div10_lo(hi uint64, lo uint64) uint64 {
	var v2 uint64
	var v5 uint64
	v2 = hi % 10
	v13 := lo & 0xffffffff
	v5 = (v2 * 0x100000000) + uint64(lo>>32)
	v18 := v5 / 10
	v2 = v5 % 10
	v5 = (v2 * 0x100000000) + v13
	return uint64(uint64(v18<<32) | (v5 / 10))
}

func u128_to_dec(hi uint64, lo uint64, digs []byte) uint32 {
	var v4 uint32
	var v5 uint32
	var v9 uint64
	var v10 uint64
	var v24 uint64
	var v41 uint64
	var v3 [48]byte
	v4 = 0
	for (hi != 0) || (lo != 0) {
		v10 = hi % 10
		v24 = lo & 0xffffffff
		v9 = (v10 * 0x100000000) + uint64(lo>>32)
		v10 = v9 % 10
		v9 = (v10 * 0x100000000) + v24
		v3[v4] = byte(uint64(48) + (v9 % uint64(10)))
		v4++
		v41 = u128_div10_lo(hi, lo)
		hi = u128_div10_hi(hi, lo)
		lo = v41
	}
	for v5 = 0; v5 < v4; v5++ {
		digs[v5] = v3[int((v4-1)-v5)]
	}
	digs[v4] = 0
	return v4
}

func limbs_mul5(limb []uint64, n uint32) uint32 {
	var v2 uint32
	var v3 uint64
	var v6 uint64
	var v7 uint64
	var v10 uint64
	var v14 uint64
	if uint32(len(limb)) < n {
		n = uint32(len(limb))
	}
	v2 = 0
	v3 = 0
	for v2 < n {
		v10 = limb[v2]
		v6 = uint64(v10 >> 62)
		v14 = uint64(v10 << 2)
		v7 = v14 + v10
		if v7 < v14 {
			v6++
		}
		v7 += v3
		if v7 < v3 {
			v6++
		}
		limb[v2] = v7
		v3 = v6
		v2++
	}
	if v3 != 0 {
		if n < 40 {
			limb[n] = v3
			n++
		}
	}
	return n
}

func limbs_shl1(limb []uint64, n uint32) uint32 {
	var v2 uint32
	var v3 uint64
	var v7 uint64
	if uint32(len(limb)) < n {
		n = uint32(len(limb))
	}
	v2 = 0
	v3 = 0
	for v2 < n {
		v7 = limb[v2]
		limb[v2] = uint64(v7<<1) | v3
		v3 = uint64(v7 >> 63)
		v2++
	}
	if v3 != 0 {
		if n < 40 {
			limb[n] = v3
			n++
		}
	}
	return n
}

func limbs_div10_rem(limb []uint64, n uint32) uint32 {
	var v2 uint32
	var v3 uint64
	var v12 uint32
	var v13 uint64
	var v17 uint64
	var v18 uint64
	var v24 uint64
	if uint32(len(limb)) < n {
		n = uint32(len(limb))
	}
	v2 = 0
	v3 = 0
	for v2 < n {
		v12 = (n - 1) - v2
		v13 = limb[v12]
		v18 = v3 % 10
		v24 = v13 & 0xffffffff
		v17 = (v18 * 0x100000000) + uint64(v13>>32)
		v18 = v17 % 10
		v17 = (v18 * 0x100000000) + v24
		limb[v12] = u128_div10_lo(v3, v13)
		v3 = v17 % 10
		v2++
	}
	return uint32(v3)
}

func limbs_zero(limb []uint64, n uint32) int {
	var v2 uint32
	if uint32(len(limb)) < n {
		n = uint32(len(limb))
	}
	for v2 = 0; v2 < n; v2++ {
		if limb[v2] != 0 {
			return 0
		}
	}
	return 1
}

func negexp_to_dec(m2 uint64, q uint32, dst []byte, mag float64) uint32 {
	var v7 uint32
	var v8 uint32
	var v9 uint32
	var v10 uint32
	var v4 [40]uint64
	var v5 [800]byte
	var v6 [800]byte
	clear(v4[:40])
	v4[0] = m2
	v7 = 1
	for v9 = 0; v9 < q; v9++ {
		v7 = limbs_mul5(v4[:], v7)
	}
	v10 = 0
	for limbs_zero(v4[:], v7) == 0 {
		v5[v10] = byte(uint32(48) + limbs_div10_rem(v4[:], v7))
		v10++
		if v7 > 1 {
			if v4[int(v7-1)] == 0 {
				v7--
			}
		}
	}
	for v8 = 0; v8 < v10; v8++ {
		v6[v8] = v5[int((v10-1)-v8)]
	}
	return uint32(emit_from_digits(dst[:], v6[:], v10, (int(v10) - int(q)), mag))
}

func posexp_to_dec(m2 uint64, q uint32, dst []byte, mag float64) uint32 {
	var v7 uint32
	var v8 uint32
	var v9 uint32
	var v10 uint32
	var v4 [40]uint64
	var v5 [800]byte
	var v6 [800]byte
	clear(v4[:40])
	v4[0] = m2
	v7 = 1
	for v9 = 0; v9 < q; v9++ {
		v7 = limbs_shl1(v4[:], v7)
	}
	v10 = 0
	for limbs_zero(v4[:], v7) == 0 {
		v5[v10] = byte(uint32(48) + limbs_div10_rem(v4[:], v7))
		v10++
		if v7 > 1 {
			if v4[int(v7-1)] == 0 {
				v7--
			}
		}
	}
	for v8 = 0; v8 < v10; v8++ {
		v6[v8] = v5[int((v10-1)-v8)]
	}
	return uint32(emit_from_digits(dst[:], v6[:], v10, int(v10), mag))
}

func emit_from_digits(dst []byte, digs []byte, nd uint32, nform int, mag float64) uint32 {
	var v5 uint64
	var v6 uint32
	var v7 uint32
	var v8 uint32
	var v43 uint32
	v8 = 0
	v7 = 1
	for v6 = v8; v6 < nd; v6++ {
		if digs[v6] != '0' {
			v7 = v6 + 1
		}
	}
	if v7 > 17 {
		if digs[17] >= '5' {
			v6 = 16
			for {
				if digs[v6] < '9' {
					digs[v6] += 1
					break
				}
				digs[v6] = '0'
				if v6 == 0 {
					digs[0] = '1'
					nform++
					v7 = 1
					v8 = v7
					break
				}
				v6--
			}
		}
		if v8 == 0 {
			v7 = 17
			v6 = 0
			v43 = 1
			for v6 < v7 {
				if digs[v6] != '0' {
					v43 = v6 + 1
				}
				v6++
			}
			v7 = v43
		}
	}
	v5 = 0
	for v6 = 0; v6 < v7; v6++ {
		v5 = (v5 * 10) + uint64(digs[v6]-48)
	}
	return uint32(emit_ecma(dst[:], 0, v5, int(v7), nform))
}

func recons(s uint64, n int, k int) float64 {
	var v5 int
	var v6 float64
	var v7 uint32
	var v14 bool
	var v22 bool
	v6 = float64(s)
	v5 = n - k
	v14 = (v5 >= 0) && (v5 <= 22)
	if v14 {
		v7 = uint32(v5)
		return float64(v6 * float64(C2D2S_P10[v7]))
	}
	v22 = (v5 < 0) && (v5 >= -22)
	if v22 {
		v7 = uint32(-float64(v5))
		return float64(v6 * float64(C2D2S_P10N[v7]))
	}
	if v5 > 0 {
		for v5 >= 8 {
			v6 *= float64(1e+08)
			v5 -= 8
		}
		for v5 > 0 {
			v6 *= float64(10)
			v5--
		}
	} else {
		v5 = int(-float64(v5))
		for v5 >= 8 {
			v6 *= float64(1e-08)
			v5 -= 8
		}
		for v5 > 0 {
			v6 = v6 / float64(10)
			v5--
		}
	}
	return float64(v6)
}

func C2_ecma_d2s_buffered(f float64, dst []byte) uint32 {
	var v3 int
	var v4 int
	var v6 int
	var v7 float64
	var v8 float64
	var v9 uint64
	var v17 bool
	var v84 bool
	var v98 bool
	if f != f {
		return uint32(emit_lit(dst[:], []byte([]byte(__str_d5b592c0)), uint32(3)))
	}
	v17 = (f != float64(0)) && ((f + f) == f)
	if v17 {
		if f < float64(0) {
			return uint32(emit_lit(dst[:], []byte([]byte(__str_c64ddf11)), uint32(9)))
		}
		return uint32(emit_lit(dst[:], []byte([]byte(__str_d0067cad)), uint32(8)))
	}
	if f == float64(0) {
		return uint32(emit_lit(dst[:], []byte([]byte(__str_5feceb66)), uint32(1)))
	}
	v7 = f
	v29 := floor_log10_pos(v7)
	v3 = v29 + 1
	v33 := 16 - v29
	v8 = v7
	if v33 > 0 {
		v6 = v33
		for v6 >= 8 {
			v8 *= float64(1e+08)
			v6 -= 8
		}
		for v6 > 0 {
			v8 *= float64(10)
			v6--
		}
	} else {
		if v33 < 0 {
			v6 = -int(v33)
			for v6 >= 8 {
				v8 *= float64(1e-08)
				v6 -= 8
			}
			for v6 > 0 {
				v8 = v8 / float64(10)
				v6--
			}
		}
	}
	v8 += float64(0.5)
	v9 = uint64(v8)
	if v9 >= 0x16345785d8a0000 {
		v9 = 0x2386f26fc10000
		v3++
	}
	v4 = 17
	for {
		v72 := (v4 > 1) && ((v9 % uint64(10)) == 0)
		if !v72 {
			break
		}
		v9 = v9 / 10
		v4--
	}
	if recons(v9, v3, v4) != v7 {
		v84 = (v9 > 0) && (recons((v9-1), v3, v4) == v7)
		if v84 {
			v9--
		} else {
			if recons((v9+1), v3, v4) == v7 {
				v9++
			} else {
				v98 = (v9 > 1) && (recons((v9-2), v3, v4) == v7)
				if v98 {
					v9 -= 2
				}
			}
		}
	}
	for v4 > 1 {
		if recons((v9/10), v3, (v4-1)) == v7 {
			v9 = v9 / 10
			v4--
		} else {
			break
		}
	}
	return uint32(emit_ecma(dst[:], 0, v9, v4, v3))
}

func C2_ecma_d2s_bits(bits uint64, mag float64, dst []byte) uint32 {
	var v5 int
	var v6 uint64
	var v7 uint64
	var v8 uint64
	var v9 uint32
	var v17 uint32
	var v53 bool
	var v58 uint64
	var v66 uint32
	var v10 [48]byte
	v16 := uint64(bits>>52) & 0x7ff
	v17 = uint32(v16)
	v19 := bits & 0xfffffffffffff
	if v17 == 0x7ff {
		if v19 != 0 {
			return uint32(emit_lit(dst[:], []byte([]byte(__str_d5b592c0)), uint32(3)))
		}
		if uint64(bits>>63) != 0 {
			return uint32(emit_lit(dst[:], []byte([]byte(__str_c64ddf11)), uint32(9)))
		}
		return uint32(emit_lit(dst[:], []byte([]byte(__str_d0067cad)), uint32(8)))
	}
	if uint64(bits<<1) == 0 {
		return uint32(emit_lit(dst[:], []byte([]byte(__str_5feceb66)), uint32(1)))
	}
	if v17 == 0 {
		v5 = -1074
		v6 = v19
	} else {
		v5 = (int(v17) - 0x3ff) - 52
		v6 = v19 | 0x10000000000000
	}
	v53 = (v5 >= 0) && (v5 <= 74)
	if v53 {
		v7 = 0
		v8 = v6
		v9 = uint32(v5)
		for v9 > 0 {
			v58 = uint64(v8 >> 63)
			v8 = uint64(v8 << 1)
			v7 = uint64(v7<<1) | v58
			v9--
		}
		v66 = u128_to_dec(v7, v8, v10[:])
		if v66 == 0 {
			return uint32(emit_lit(dst[:], []byte([]byte(__str_5feceb66)), uint32(1)))
		}
		return uint32(emit_from_digits(dst[:], v10[:], v66, int(v66), float64(0)))
	}
	if v5 < 0 {
		return uint32(negexp_to_dec(v6, uint32(-v5), dst[:], mag))
	}
	return uint32(posexp_to_dec(v6, uint32(v5), dst[:], mag))
}
