// SPDX-License-Identifier: Apache-2.0 OR MIT
//go:build goexperiment.simd && amd64

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=656a9ef2cbf3abb013fbeff19110a953e0ad0d1209ed513843d62b7d84446192
package c2strsimd

import (
	"math/bits"
	"simd/archsimd"
)

func __avx2() int {
	return 1
}

func c2_memchr_scalar(src []byte, len_ uint64, target byte) int64 {
	var v3 uint64
	if uint64(len(src)) < len_ {
		len_ = uint64(len(src))
	}
	for v3 = 0; v3 < len_; v3++ {
		if src[v3] == target {
			return int64(v3)
		}
	}
	return -1
}

func c2_memchr_avx2(src []byte, len_ uint64, target byte) int64 {
	var v6 uint64
	var v7 uint64
	var v9 int
	if uint64(len(src)) < len_ {
		len_ = uint64(len(src))
	}
	v9 = 0
	v7 = 0
	v6 = v7
	for (v6 + 32) <= len_ {
		v23 := uint32(archsimd.LoadUint8x32(src[v6:][:32]).Equal(archsimd.BroadcastUint8x32(target)).ToBits())
		if v23 != 0 {
			v7 = v6 + uint64(bits.TrailingZeros32(v23))
			v9 = 1
			v6 = len_
		} else {
			v6 += 32
		}
	}
	archsimd.ClearAVXUpperBits()
	if v9 != 0 {
		return int64(v7)
	}
	for v6 < len_ {
		if src[v6] == target {
			return int64(v6)
		}
		v6++
	}
	return -1
}

func C2_memchr(src []byte, len_ uint64, target byte) int64 {
	if uint64(len(src)) < len_ {
		len_ = uint64(len(src))
	}
	if archsimd.X86.AVX2() {
		return int64(c2_memchr_avx2(src[:], len_, target))
	}
	return int64(c2_memchr_scalar(src[:], len_, target))
}

func C2_strpos(haystack []byte, h_len uint64, needle []byte, n_len uint64) int64 {
	var v7 uint64
	var v40 []byte
	var v46 int
	if n_len == 0 {
		return 0
	}
	if h_len < n_len {
		return -1
	}
	if n_len == 1 {
		return int64(C2_memchr(haystack[:], h_len, needle[0]))
	}
	for v7 = 0; v7 < ((h_len - n_len) + 1); v7++ {
		if haystack[v7] == needle[0] {
			if haystack[int((v7+n_len)-1)] == needle[int(n_len-1)] {
				v40 = haystack[int(v7+1):]
				v46 = func(a, b []byte, n int) int {
					for i := 0; i < n && i < len(a) && i < len(b); i++ {
						if a[i] != b[i] {
							if a[i] < b[i] {
								return -1
							}
							return 1
						}
					}
					return 0
				}(v40[:], needle[1:], int(n_len-2))
				if (n_len <= 2) || (v46 == 0) {
					return int64(v7)
				}
			}
		}
	}
	return -1
}

func c2_strtoupper_scalar(dst []byte, src []byte, len_ uint64) {
	var v3 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 := src[v3]
		v14 := func() uint64 {
			if (v8 - 'a') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v3] = v8 - (byte(v14) * 32)
	}
}

func c2_strtoupper_avx2(dst []byte, src []byte, len_ uint64) {
	var v11 uint64
	v11 = 0
	for {
		v21 := v11 + 32
		if !(v21 <= len_) {
			break
		}
		v25 := archsimd.LoadUint8x32(src[v11:][:32])
		v26 := v25.Sub(archsimd.BroadcastUint8x32(byte(97)))
		v25.Sub(v26.Min(archsimd.BroadcastUint8x32(byte(25))).Equal(v26).ToInt8x32().AsUint8x32().And(archsimd.BroadcastUint8x32(byte(32)))).Store(dst[v11:][:32])
		v11 = v21
	}
	archsimd.ClearAVXUpperBits()
	for v11 < len_ {
		v39 := src[v11]
		v45 := func() uint64 {
			if (v39 - 'a') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v11] = v39 - (byte(v45) * 32)
		v11++
	}
}

func C2_strtoupper(dst []byte, src []byte, len_ uint64) {
	if archsimd.X86.AVX2() {
		c2_strtoupper_avx2(dst[:], src[:], len_)
		return
	}
	c2_strtoupper_scalar(dst[:], src[:], len_)
}

func c2_strtolower_scalar(dst []byte, src []byte, len_ uint64) {
	var v3 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 := src[v3]
		v14 := func() uint64 {
			if (v8 - 'A') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v3] = v8 + (byte(v14) * 32)
	}
}

func c2_strtolower_avx2(dst []byte, src []byte, len_ uint64) {
	var v11 uint64
	v11 = 0
	for {
		v21 := v11 + 32
		if !(v21 <= len_) {
			break
		}
		v25 := archsimd.LoadUint8x32(src[v11:][:32])
		v26 := v25.Sub(archsimd.BroadcastUint8x32(byte(65)))
		v25.Add(v26.Min(archsimd.BroadcastUint8x32(byte(25))).Equal(v26).ToInt8x32().AsUint8x32().And(archsimd.BroadcastUint8x32(byte(32)))).Store(dst[v11:][:32])
		v11 = v21
	}
	archsimd.ClearAVXUpperBits()
	for v11 < len_ {
		v39 := src[v11]
		v45 := func() uint64 {
			if (v39 - 'A') <= 25 {
				return 1
			}
			return 0
		}()
		dst[v11] = v39 + (byte(v45) * 32)
		v11++
	}
}

func C2_strtolower(dst []byte, src []byte, len_ uint64) {
	if archsimd.X86.AVX2() {
		c2_strtolower_avx2(dst[:], src[:], len_)
		return
	}
	c2_strtolower_scalar(dst[:], src[:], len_)
}

func c2_mb_strlen_utf8_scalar(src []byte, byte_len uint64) uint64 {
	var v2 uint64
	var v4 uint64
	var v10 byte
	if uint64(len(src)) < byte_len {
		byte_len = uint64(len(src))
	}
	v2 = 0
	for v4 = 0; v4 < byte_len; v4++ {
		v10 = src[v4] & 0xc0
		if v10 != 0x80 {
			v2++
		}
	}
	return v2
}

func c2_mb_strlen_utf8_avx2(src []byte, byte_len uint64) uint64 {
	var v6 uint64
	var v7 uint64
	var v35 byte
	if uint64(len(src)) < byte_len {
		byte_len = uint64(len(src))
	}
	v6 = 0
	v7 = v6
	for {
		v16 := v7 + 32
		if !(v16 <= byte_len) {
			break
		}
		v6 += (32 - uint64(bits.OnesCount32(uint32(archsimd.LoadUint8x32(src[v7:][:32]).And(archsimd.BroadcastUint8x32(byte(192))).Equal(archsimd.BroadcastUint8x32(byte(128))).ToBits()))))
		v7 = v16
	}
	archsimd.ClearAVXUpperBits()
	for v7 < byte_len {
		v35 = src[v7] & 0xc0
		if v35 != 0x80 {
			v6++
		}
		v7++
	}
	return v6
}

func C2_mb_strlen_utf8(src []byte, byte_len uint64) uint64 {
	if uint64(len(src)) < byte_len {
		byte_len = uint64(len(src))
	}
	if archsimd.X86.AVX2() {
		return uint64(c2_mb_strlen_utf8_avx2(src[:], byte_len))
	}
	return uint64(c2_mb_strlen_utf8_scalar(src[:], byte_len))
}

func C2_ltrim_offset(src []byte, len_ uint64, cutset_bitmap_32b []byte) uint64 {
	var v3 uint64
	for v3 = 0; v3 < len_; v3++ {
		v8 := src[v3]
		v14 := v8 & 7
		v17 := uint64(uint64(cutset_bitmap_32b[int(uint64(uint64(v8)>>3))])>>v14) & 1
		if byte(v17) == 0 {
			return v3
		}
	}
	return len_
}

func C2_rtrim_len(src []byte, len_ uint64, cutset_bitmap_32b []byte) uint64 {
	for len_ > 0 {
		v7 := src[int(len_-1)]
		v13 := v7 & 7
		v16 := uint64(uint64(cutset_bitmap_32b[int(uint64(uint64(v7)>>3))])>>v13) & 1
		if byte(v16) == 0 {
			break
		}
		len_--
	}
	return len_
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	__avx2_IRCost                   = uint64(2)
	C2_memchr_scalar_IRCost         = uint64(11)
	C2_memchr_avx2_IRCost           = uint64(51)
	C2_memchr_IRCost                = uint64(5)
	C2_strpos_IRCost                = uint64(58)
	C2_strtoupper_scalar_IRCost     = uint64(19)
	C2_strtoupper_avx2_IRCost       = uint64(61)
	C2_strtoupper_IRCost            = uint64(4)
	C2_strtolower_scalar_IRCost     = uint64(19)
	C2_strtolower_avx2_IRCost       = uint64(61)
	C2_strtolower_IRCost            = uint64(4)
	C2_mb_strlen_utf8_scalar_IRCost = uint64(16)
	C2_mb_strlen_utf8_avx2_IRCost   = uint64(51)
	C2_mb_strlen_utf8_IRCost        = uint64(5)
	C2_ltrim_offset_IRCost          = uint64(21)
	C2_rtrim_len_IRCost             = uint64(21)
)
