// SPDX-License-Identifier: BUSL-1.1
//go:build archtime_generate

package engine

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
	"testing"
	"strings"

	"github.com/hazyhaar/js55/pkg/js55/parser"
)

// TestArchtimeRegenerate is the actual table generator. It uses the SAME
// fingerprint implementation as the engine, not a hand-maintained second hash.
func TestArchtimeRegenerate(t *testing.T) {
	cmd := exec.Command("cue", "export", "./archtime_spec/spec.cue", "--out", "json")
	b, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("CUE: %v %s", err, b)
	}
	var spec struct {
		Funcs    []struct{ Name, Tag, Src string }
		Contract struct {
			MaxCallbackPoints, GasBase, GasPerPoint int
			Input, Output, Scope, Unknown           string
			LargeAtomic, Checkpoint                 string
		}
	}
	if err = json.Unmarshal(b, &spec); err != nil {
		t.Fatal(err)
	}
	if len(spec.Funcs) != 7 {
		t.Fatal("closed binding must contain exactly 7 bodies")
	}
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by TestArchtimeRegenerate; DO NOT EDIT.\n// CUE contract SHA256: %x\npackage engine\n\n", sha256.Sum256(b))
	fmt.Fprintln(&out, "func recognizeArchtimeGeometry(c *Chunk) { switch c.archtimeHash {")
	lengths := map[int]bool{}
	seen := map[string]bool{}
	for _, f := range spec.Funcs {
		for _, strict := range []bool{false, true} {
			p, e := parser.Parse(f.Src, parser.Options{})
			if e != nil {
				t.Fatal(e)
			}
			c, e := CompileMode(NewHeap(), p, "binding", strict)
			if e != nil {
				t.Fatal(e)
			}
			var fn *Chunk
			if f.Tag == "archtimeTagComputeVertexNormals" || f.Tag == "archtimeTagNormalizeNormals" {
				bThree, _ := os.ReadFile("/devhoros/GAFP/audits/comparatif-chromium-js55-20260909/mutations/input-three-source")
				pThree, _ := parser.Parse(string(bThree), parser.Options{})
				cThree, _ := CompileMode(NewHeap(), pThree, "binding", strict)
				var search func(chk *Chunk)
				search = func(chk *Chunk) {
					for _, k := range chk.Consts {
						if k.Kind == ConstFunction {
							name := k.Fn.Name
							if name != "" && (f.Name == name || f.Name[strings.LastIndex(f.Name, ".")+1:] == name) {
								if fn != nil {
									t.Fatal("multiple bodies")
								}
								fn = k.Fn
							}
							search(k.Fn)
						}
					}
				}
				search(cThree)
			} else {
				var search func(chk *Chunk)
				search = func(chk *Chunk) {
					for _, k := range chk.Consts {
						if k.Kind == ConstFunction {
							name := k.Fn.Name
							if name != "" && (f.Name == name || f.Name[strings.LastIndex(f.Name, ".")+1:] == name) {
								if fn != nil {
									t.Fatal("multiple bodies")
								}
								fn = k.Fn
							}
							search(k.Fn)
						}
					}
				}
				search(c)
			}
			if fn == nil {
				t.Fatal("missing body")
			}
			hash := hashChunk(fn)
			if hash == "" {
				t.Fatalf("unproved scope: %s", f.Name)
			}
			lengths[len(fn.Code)] = true
			if !seen[hash] { seen[hash] = true; fmt.Fprintf(&out, "case %q: // %s strict=%t; full body sha256=%x\nc.archtimeTag=%s\n", hash, f.Name, strict, sha256.Sum256([]byte(f.Src)), f.Tag) }
		}
	}
	fmt.Fprintln(&out, "}}")
	fmt.Fprintf(&out, "const ( archtimeMaxCallbackPoints = %d; archtimeGasBase = %d; archtimeGasPerPoint = %d; archtimeInputContract = %q; archtimeOutputContract = %q; archtimeScopeContract = %q; archtimeLargeAtomicContract = %q; archtimeCheckpointContract = %q )\n", spec.Contract.MaxCallbackPoints, spec.Contract.GasBase, spec.Contract.GasPerPoint, spec.Contract.Input, spec.Contract.Output, spec.Contract.Scope, spec.Contract.LargeAtomic, spec.Contract.Checkpoint)
	var sorted []int
	for n := range lengths {
		sorted = append(sorted, n)
	}
	sort.Ints(sorted)
	fmt.Fprint(&out, "var archtimeCodeLengths = [...]int{")
	for _, n := range sorted {
		fmt.Fprintf(&out, "%d,", n)
	}
	fmt.Fprintln(&out, "}")
	data, err := format.Source(out.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	if err = os.WriteFile("archtime_table_generated.go", data, 0644); err != nil {
		t.Fatal(err)
	}
}
