// SPDX-License-Identifier: BUSL-1.1
// Code generated by TestArchtimeRegenerate; DO NOT EDIT.
// CUE contract SHA256: c45d478c9a0c1dcfdbbcb7a4b157b6b6a11cf4db4eb0de250e657babb5ab3f9f
package engine

func recognizeArchtimeGeometry(c *Chunk) {
	switch c.archtimeHash {
	case "cc1c75f1ced683f76ccdce7838da6274ce582a370d086445870618dbcd733da0": // Box3.setFromBufferAttribute strict=false; full body sha256=28126ce5c9efa95849edf5ef18817e46a34b347a2539c8af3bab20f16ef67b8a
		c.archtimeTag = archtimeTagBox3SetFromBufferAttribute
	case "bd05d4cb484815a61b7ac54f5d92c87dcdbf55cfaf2c82f098f06a3fbb9427c0": // Box3.setFromBufferAttribute strict=true; full body sha256=28126ce5c9efa95849edf5ef18817e46a34b347a2539c8af3bab20f16ef67b8a
		c.archtimeTag = archtimeTagBox3SetFromBufferAttribute
	case "21d27e6b9c721ce71ff9f700bbbf49026955106daa9a51a24b064084d27da296": // Vector3.set strict=false; full body sha256=174c9d151305dd66f081cf08a926f2f290a82d82299b05ea54e6f16f0227dbf0
		c.archtimeTag = archtimeTagVector3Set
	case "357f7d66ea2c7c2eb7b2887ff55b3a7e84624901507aa2ad2ba8d31b2aa675cc": // Vector3.set strict=true; full body sha256=174c9d151305dd66f081cf08a926f2f290a82d82299b05ea54e6f16f0227dbf0
		c.archtimeTag = archtimeTagVector3Set
	case "716819f9b3222e4185b0181999fdf5723abd35afda97faddddc1f2b21953c1c5": // BufferAttribute.getX strict=false; full body sha256=b2dbedd77bdedec614660cbbc01a7129c50ddc34c08177912f3540035fadbc2b
		c.archtimeTag = archtimeTagBufferAttributeGetX
	case "9cfa49b07c4b38629976a29f7683cca50302f5b3edbf0e04e54e9b853762ed58": // BufferAttribute.getX strict=true; full body sha256=b2dbedd77bdedec614660cbbc01a7129c50ddc34c08177912f3540035fadbc2b
		c.archtimeTag = archtimeTagBufferAttributeGetX
	case "b672deeaf98081d4ce6d06bc22966c079a42cce432afc14d53e7b399d535b286": // BufferAttribute.getY strict=false; full body sha256=fc55a6f6e710c6795a60243a3f2f162b7d33a6b8b93e4a01d7ad7dcd5a55d87e
		c.archtimeTag = archtimeTagBufferAttributeGetY
	case "84b163acf11b72c86f71f7da040b54bb2493d64f9a7636c7023b41a5828f4502": // BufferAttribute.getY strict=true; full body sha256=fc55a6f6e710c6795a60243a3f2f162b7d33a6b8b93e4a01d7ad7dcd5a55d87e
		c.archtimeTag = archtimeTagBufferAttributeGetY
	case "ce9716c57473c97c925bbf6f3ba493ba0275bf0e0ace39d1da81f263e7762ba6": // BufferAttribute.getZ strict=false; full body sha256=7f8f39ba2b628d5c21f8869691980f072bb9a28e9c1db9499dd2eed92006de56
		c.archtimeTag = archtimeTagBufferAttributeGetZ
	case "b26706737a5a4bda87830b9765d9933ecc5ff6fd5e09440920fd25374e36b109": // BufferAttribute.getZ strict=true; full body sha256=7f8f39ba2b628d5c21f8869691980f072bb9a28e9c1db9499dd2eed92006de56
		c.archtimeTag = archtimeTagBufferAttributeGetZ
	case "f197099c26015117ae8c5ff59312b0e2daafb98fe2bd4066351bd1a7d2406cda": // BufferGeometry.computeVertexNormals strict=false; full body sha256=c2aa3ed2056857f9299d810d81dfc222c9eff76e82921dd863cfba5ed213d749
		c.archtimeTag = archtimeTagComputeVertexNormals
	case "c650bbee5f689f82826eee1a5b059ef4380ccfa53abea1b70908e534f228866d": // BufferGeometry.normalizeNormals strict=false; full body sha256=65143eb63b95fb157ff770e9c3aaf308f48c167240c16782314b73ba95aa2065
		c.archtimeTag = archtimeTagNormalizeNormals
	}
}

const (
	archtimeMaxCallbackPoints   = 4096
	archtimeGasBase             = 2048
	archtimeGasPerPoint         = 1024
	archtimeInputContract       = "ordinary data slots; Float32Array; normalized=false; itemSize=3; exact count; aligned bounded fixed backing"
	archtimeOutputContract      = "ordinary min/max with writable own x/y/z and structurally proved set"
	archtimeScopeContract       = "whole compiled ordinary body; no outer lexical access; compiler TDZ token only"
	archtimeLargeAtomicContract = "maxCallbackPoints limits calls with OnCheckpoint configured; otherwise exact backing length and remaining gas bound the call; check interruption again before publishing output"
	archtimeCheckpointContract  = "unchanged cadence; any crossing uses generic code, without native callbacks or prefix replay"
)

var archtimeCodeLengths = [...]int{22, 28, 72, 197, 588, 1494}
