// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=e4005e9f54db07720a8d8b8a2e85fdc8cb59e5acd6488a85d20e05af5319c47f
package engine

func C2_v8_parseint_is_digit(x int, radix int) int {
	v3 := func() int {
		if x >= 48 {
			return 1
		}
		return 0
	}()
	v5 := func() int {
		if x <= 57 {
			return 1
		}
		return 0
	}()
	v6 := func() int {
		if (v3 != 0) && (v5 != 0) {
			return 1
		}
		return 0
	}()
	v9 := func() int {
		if x < (48 + radix) {
			return 1
		}
		return 0
	}()
	v10 := func() int {
		if (v6 != 0) && (v9 != 0) {
			return 1
		}
		return 0
	}()
	v12 := func() int {
		if radix > 10 {
			return 1
		}
		return 0
	}()
	v14 := func() int {
		if x >= 97 {
			return 1
		}
		return 0
	}()
	v15 := func() int {
		if (v12 != 0) && (v14 != 0) {
			return 1
		}
		return 0
	}()
	v20 := func() int {
		if x < ((97 + radix) - 10) {
			return 1
		}
		return 0
	}()
	v21 := func() int {
		if (v15 != 0) && (v20 != 0) {
			return 1
		}
		return 0
	}()
	v22 := func() int {
		if (v10 != 0) || (v21 != 0) {
			return 1
		}
		return 0
	}()
	v26 := func() int {
		if x >= 65 {
			return 1
		}
		return 0
	}()
	v27 := func() int {
		if (v12 != 0) && (v26 != 0) {
			return 1
		}
		return 0
	}()
	v32 := func() int {
		if x < ((65 + radix) - 10) {
			return 1
		}
		return 0
	}()
	v33 := func() int {
		if (v27 != 0) && (v32 != 0) {
			return 1
		}
		return 0
	}()
	v34 := func() int {
		if (v22 != 0) || (v33 != 0) {
			return 1
		}
		return 0
	}()
	return v34
}
