// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=56eb934cb346080621f6013444a3d86f14ecd92114920e2aaa1985fa0e380c16
package engine

func C2_v8_parseint_r16_exact(s []byte, n int, out_number *uint64) int {
	var v3 uint64
	var v5 int
	var v7 int
	var v12 byte
	var v13 int
	var v18 bool
	var v25 bool
	var v34 bool
	var v46 bool
	v3 = 0
	v5 = 0
	for v7 = 0; v7 < n; v7++ {
		v12 = s[v7]
		v18 = (v12 >= '0') && (v12 <= '9')
		if v18 {
			v13 = int(v12 - 48)
		} else {
			v25 = (v12 >= 'a') && (v12 <= 'f')
			if v25 {
				v13 = int((v12 - 0x61) + 10)
			} else {
				v34 = (v12 >= 'A') && (v12 <= 'F')
				if v34 {
					v13 = int((v12 - 0x41) + 10)
				} else {
					v13 = -1
				}
			}
		}
		v46 = (v13 >= 0) && (uint64(v3>>53) == 0)
		if v46 {
			v3 = (v3 * 16) + uint64(v13)
			v5 = v7 + 1
		} else {
			break
		}
	}
	*out_number = v3
	return v5
}
