// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ea4e715cac62c0c4b133482b194fb9b6b0e6829ca72aaf32ea7e67d1ab02d637
package engine

func C2_v8_parseint_digit(c int, radix int) int {
	var v7 int
	var v22 bool
	var v28 bool
	var v36 bool
	v7 = min(radix, 10)
	v12 := radix - 10
	v22 = (c >= 48) && (c < (48 + v7))
	if v22 {
		return (c - 48)
	} else {
		v28 = (c >= 97) && (c < (97 + v12))
		if v28 {
			return ((c - 97) + 10)
		} else {
			v36 = (c >= 65) && (c < (65 + v12))
			if v36 {
				return ((c - 65) + 10)
			} else {
				return -1
			}
		}
	}
}
