// SPDX-License-Identifier: BUSL-1.1
// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=e4cce79d6f1496f24de2b1357132661179513b5cdcb42259c0caa61d9ba2aaaf
package engine

func C2_v8_parseint_radix_ok(radix int) int {
	var v5 bool
	var v8 int
	v5 = (radix >= 2) && (radix <= 36)
	v8 = func() int {
		if v5 {
			return 1
		}
		return 0
	}()
	return v8
}
