// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=84155ca0b7a82d8f9c193a9c563f6f118a7c8164bb993c0387e4a43383f2b76a
package engine

func C2_v8_parseint_is_binary_digit(x int) int {
	var v8 int
	v8 = func() int {
		if (x == 48) || (x == 49) {
			return 1
		}
		return 0
	}()
	return v8
}
