// SPDX-License-Identifier: BUSL-1.1
// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=d0bf85b2ef197a3bf3174b6dd6061efd9bc7868ce2b8b1630209f2f59725a1b0
package engine

func C2_v8_parseint_skip_zeros(s []byte, n int) int {
	var v2 int
	for v2 = 0; v2 < n && s[v2] == '0'; v2++ {
	}
	return v2
}
