// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=9d47d430faf5929db31955a98ceacd629110aa30f34475eb33c421e402935d08
package engine

func C2js_parseint_digit(c int32, radix int32) int32 {
	var v28 bool
	var v36 bool
	v7 := min(radix, int32(10))
	v12 := radix - 10
	v22 := (c >= 48) && (c < (int32(48) + v7))
	if v22 {
		return int32(c - 48)
	} else {
		v28 = (c >= 97) && (c < (int32(97) + v12))
		if v28 {
			return int32((c - 97) + 10)
		} else {
			v36 = (c >= 65) && (c < (int32(65) + v12))
			if v36 {
				return int32((c - 65) + 10)
			} else {
				return -1
			}
		}
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2js_parseint_digit_IRCost = uint64(44)
