// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=08a6a7f22f40ca838914c9b47d811df25080b89a4a5ac1bab5b6479f57bcc35a
package engine

func C2js_parseint_skip_zeros(s []byte, n int32) int32 {
	var v2 int32
	for v2 = 0; v2 < n && s[v2] == '0'; v2++ {
	}
	return v2
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2js_parseint_skip_zeros_IRCost = uint64(11)
