// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=e2d9a5414b76671af606f2afe0a6634d5955da655f6e54721021830eca5be813
package engine

func C2js_parseint_is_binary_digit(x int32) int32 {
	v8 := func() int32 {
		if (x == 48) || (x == 49) {
			return int32(1)
		}
		return int32(0)
	}()
	return int32(v8)
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2js_parseint_is_binary_digit_IRCost = uint64(9)
