// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=930b7b129ed5c1700e1287d9e5eced9e1454c87f3086cbf9e6b87dd7f8b00103
package engine

func in_range(v uint32, lo uint32, n uint32) uint32 {
	return uint32(uint64((uint64(v-lo) - uint64(n)) >> 63))
}

func C2js_parseint_is_digit(c int32, radix int32) int32 {
	v3 := uint32(c)
	v5 := uint32(radix)
	v12 := in_range(v5, uint32(11), uint32(26)) * (v5 - 10)
	return int32((in_range(v3, uint32(48), (v5-v12)) | in_range(v3, uint32(0x61), v12)) | in_range(v3, uint32(0x41), v12))
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	In_range_IRCost               = uint64(10)
	C2js_parseint_is_digit_IRCost = uint64(24)
)
