// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=ac16688d34dea5ccc261a75322823d8cc7bd8bbde284d6522950035710dcf2f5
package engine

func C2js_parseint_radix_ok(radix int32) int32 {
	v5 := (radix >= 2) && (radix <= 36)
	v8 := func() int32 {
		if v5 {
			return int32(1)
		}
		return int32(0)
	}()
	return int32(v8)
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const C2js_parseint_radix_ok_IRCost = uint64(9)
