// SPDX-License-Identifier: Apache-2.0 OR MIT

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=8cb09dca64c4393836d53ee3269c357b8042d74988d0d069bf6f0644622fa523
package geometry

import "math"

func Archtime_bounds_xyz(positions []float32, nfloats uint64, out []float64) {
	var v209 uint64
	var v210 float64
	var v211 float64
	var v212 float64
	var v213 float64
	var v214 float64
	var v215 float64
	var v232 float64
	var v236 float64
	var v240 float64
	v210 = float64(positions[0])
	v211 = float64(positions[1])
	v212 = float64(positions[2])
	v213 = v210
	v214 = v211
	v215 = v212
	for v209 = 3; v209 < nfloats; v209 += 3 {
		v232 = float64(positions[v209])
		v236 = float64(positions[v209+1])
		v240 = float64(positions[v209+2])
		if v232 < v210 {
			v210 = v232
		}
		if v236 < v211 {
			v211 = v236
		}
		if v240 < v212 {
			v212 = v240
		}
		if v232 > v213 {
			v213 = v232
		}
		if v236 > v214 {
			v214 = v236
		}
		if v240 > v215 {
			v215 = v240
		}
	}
	out[0] = v210
	out[1] = v211
	out[2] = v212
	out[3] = v213
	out[4] = v214
	out[5] = v215
}

func Archtime_sphere_xyz(positions []float32, nfloats uint64, out []float64) {
	var v346 uint64
	var v347 float64
	var v348 float64
	var v349 float64
	var v350 float64
	var v351 float64
	var v352 float64
	var v353 float64
	var v354 float64
	var v355 float64
	var v363 float64
	var v388 float64
	var v391 float64
	var v394 float64
	var v409 float64
	var v410 float64
	var v411 float64
	var v420 float64
	v347 = float64(positions[0])
	v348 = float64(positions[1])
	v349 = float64(positions[2])
	v350 = v347
	v351 = v348
	v352 = v349
	for v346 = 3; v346 < nfloats; v346 += 3 {
		v353 = float64(positions[v346])
		v354 = float64(positions[v346+1])
		v355 = float64(positions[v346+2])
		if v353 < v347 {
			v347 = v353
		}
		if v354 < v348 {
			v348 = v354
		}
		if v355 < v349 {
			v349 = v355
		}
		if v353 > v350 {
			v350 = v353
		}
		if v354 > v351 {
			v351 = v354
		}
		if v355 > v352 {
			v352 = v355
		}
	}
	v388 = (v347 + v350) * float64(0.5)
	v391 = (v348 + v351) * float64(0.5)
	v394 = (v349 + v352) * float64(0.5)
	v363 = float64(0)
	for v346 = 0; v346 < nfloats; v346 += 3 {
		v353 = float64(positions[v346])
		v354 = float64(positions[v346+1])
		v355 = float64(positions[v346+2])
		v409 = v353 - v388
		v410 = v354 - v391
		v411 = v355 - v394
		v420 = float64(float64(v409*v409)+float64(v410*v410)) + float64(v411*v411)
		if v420 > v363 {
			v363 = v420
		}
	}
	out[0] = v388
	out[1] = v391
	out[2] = v394
	out[3] = math.Sqrt(v363)
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	Archtime_bounds_xyz_IRCost = uint64(61)
	Archtime_sphere_xyz_IRCost = uint64(115)
)
