// SPDX-License-Identifier: Apache-2.0 OR MIT

// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=9873097e43a407d52530fa96e43846258fe8f880a111ac31bdec22aea880a45d
package geometry

import "math"

func accumulate_one(pos []float32, idx []uint32, nor []float32, t uint64) {
	var v28 float64
	var v29 float64
	var v30 float64
	var v31 float64
	var v32 float64
	var v33 float64
	var v34 float64
	var v35 float64
	var v36 float64
	var v70 float64
	var v74 float64
	var v78 float64
	var v89 float64
	var v90 float64
	var v91 float64
	var v92 float64
	var v93 float64
	var v94 float64
	var v97 float64
	var v100 float64
	var v103 float64
	v38 := t * 3
	v52 := uint64(idx[v38]) * 3
	v55 := uint64(idx[v38+1]) * 3
	v58 := uint64(idx[v38+2]) * 3
	v62 := v52 + 1
	v66 := v52 + 2
	v70 = float64(pos[v55])
	v72 := v55 + 1
	v74 = float64(pos[v72])
	v76 := v55 + 2
	v78 = float64(pos[v76])
	v82 := v58 + 1
	v86 := v58 + 2
	v89 = float64(pos[v58]) - v70
	v90 = float64(pos[v82]) - v74
	v91 = float64(pos[v86]) - v78
	v92 = float64(pos[v52]) - v70
	v93 = float64(pos[v62]) - v74
	v94 = float64(pos[v66]) - v78
	v97 = (v90 * v94) - (v91 * v93)
	v100 = (v91 * v92) - (v89 * v94)
	v103 = (v89 * v93) - (v90 * v92)
	v28 = float64(nor[v52])
	v29 = float64(nor[v62])
	v30 = float64(nor[v66])
	v31 = float64(nor[v55])
	v32 = float64(nor[v72])
	v33 = float64(nor[v76])
	v34 = float64(nor[v58])
	v35 = float64(nor[v82])
	v36 = float64(nor[v86])
	v28 += v97
	v29 += v100
	v30 += v103
	v31 += v97
	v32 += v100
	v33 += v103
	v34 += v97
	v35 += v100
	v36 += v103
	nor[v52] = float32(v28)
	nor[v62] = float32(v29)
	nor[v66] = float32(v30)
	nor[v55] = float32(v31)
	nor[v72] = float32(v32)
	nor[v76] = float32(v33)
	nor[v58] = float32(v34)
	nor[v82] = float32(v35)
	nor[v86] = float32(v36)
}

func normalize_one(nor []float32, v uint64) {
	var v7 float64
	var v11 float64
	var v15 float64
	var v19 float64
	v9 := v * 3
	v11 = float64(nor[v9])
	v15 = float64(nor[v9+1])
	v19 = float64(nor[v9+2])
	v25 := math.Sqrt(((v11 * v11) + (v15 * v15)) + (v19 * v19))
	if v25 == float64(0) {
		v7 = float64(1)
	} else {
		v7 = float64(1) / v25
	}
	nor[v9] = float32(v11 * v7)
	nor[v9+1] = float32(v15 * v7)
	nor[v9+2] = float32(v19 * v7)
}

func Archtime_accumulate_block(pos []float32, idx []uint32, nor []float32, t0 uint64) {
	accumulate_one(pos, idx[:], nor, t0)
	accumulate_one(pos, idx[:], nor, (t0 + 1))
	accumulate_one(pos, idx[:], nor, (t0 + 2))
	accumulate_one(pos, idx[:], nor, (t0 + 3))
}

func Archtime_normalize_range(nor []float32, cursor uint64, n uint64, last []float64, last_ok *uint64) {
	var v5 uint64
	var v12 float64
	var v243 uint64
	var v245 float64
	var v249 float64
	var v253 float64
	var v259 float64
	if n == 0 {
		return
	}
	for v5 = 0; v5 < n; v5++ {
		v243 = (cursor + v5) * 3
		v245 = float64(nor[v243])
		v249 = float64(nor[v243+1])
		v253 = float64(nor[v243+2])
		v259 = math.Sqrt(((v245 * v245) + (v249 * v249)) + (v253 * v253))
		if v259 == float64(0) {
			v12 = float64(1)
		} else {
			v12 = float64(1) / v259
		}
		last[0] = v245 * v12
		last[1] = v249 * v12
		last[2] = v253 * v12
		nor[v243] = float32(last[0])
		nor[v243+1] = float32(last[1])
		nor[v243+2] = float32(last[2])
		*last_ok = 1
	}
}

func Archtime_normalize_block(nor []float32, v0 uint64) {
	var v2 [3]float64
	var v3 [1]uint64
	v2[0] = float64(0)
	v2[1] = float64(0)
	v2[2] = float64(0)
	v3[0] = 0
	Archtime_normalize_range(nor, v0, uint64(4), v2[:], &v3[0])
}

func Archtime_normals_begin(npos uint64, nidx uint64, nnorm uint64, state []uint64, nstate uint64, flags uint64) int {
	_ = state[7]
	if nstate < 8 {
		return 0
	}
	if ((npos == 0) || ((npos % uint64(3)) != 0)) || (npos != nnorm) {
		return 0
	}
	if (nidx % uint64(3)) != 0 {
		return 0
	}
	v29 := flags & 2
	if v29 == 0 {
		if nidx == 0 {
			return 0
		}
	}
	state[0] = 0
	v36 := flags & 2
	if v36 != 0 {
		state[0] = 2
	}
	state[1] = 0
	state[2] = npos / 3
	state[3] = nidx / 3
	state[4] = npos
	state[5] = nidx
	state[6] = flags | 1
	state[7] = 0
	return 1
}

func Archtime_normals_step(pos []float32, idx []uint32, nor []float32, state []uint64, nstate uint64, budget uint64, last []float64, last_ok *uint64) int {
	var v8 uint64
	var v9 uint64
	var v13 uint64
	var v15 uint64
	var v29 uint64
	var v31 uint64
	var v45 bool
	var v47 uint64
	var v65 bool
	var v72 bool
	var v89 bool
	if nstate < 8 {
		return 0
	}
	v21 := state[6] & 1
	if v21 == 0 {
		return 0
	}
	v8 = state[0]
	v9 = state[1]
	v29 = state[2]
	v31 = state[3]
	if v8 > 3 {
		return 0
	}
	v13 = 0
	if budget == 0 {
		state[7] = 0
		if v8 == 3 {
			return 1
		}
		return 1
	}
	if v8 == 0 {
		if v9 > v29 {
			return 0
		}
		for {
			v45 = (v13 < budget) && (v9 < v29)
			if !v45 {
				break
			}
			v47 = v9 * 3
			nor[v47] = float32(0)
			nor[v47+1] = float32(0)
			nor[v47+2] = float32(0)
			v9++
			v13++
		}
		if v9 == v29 {
			v8 = 1
			v9 = 0
		}
	}
	if v8 == 1 {
		if v9 > v31 {
			return 0
		}
		for {
			v65 = (v13 < budget) && (v9 < v31)
			if !v65 {
				break
			}
			v72 = ((v31 - v9) >= 4) && ((budget - v13) >= 4)
			if v72 {
				Archtime_accumulate_block(pos, idx[:], nor, v9)
				v9 += 4
				v13 += 4
			} else {
				accumulate_one(pos, idx[:], nor, v9)
				v9++
				v13++
			}
		}
		if v9 == v31 {
			v8 = 2
			v9 = 0
		}
	}
	if v8 == 2 {
		if v9 > v29 {
			return 0
		}
		for {
			v89 = (v13 < budget) && (v9 < v29)
			if !v89 {
				break
			}
			v15 = budget - v13
			if v15 > (v29 - v9) {
				v15 = v29 - v9
			}
			Archtime_normalize_range(nor, v9, v15, last, last_ok)
			v9 += v15
			v13 += v15
		}
		if v9 == v29 {
			v8 = 3
			v9 = 0
		}
	}
	state[0] = v8
	state[1] = v9
	state[7] = v13
	return 1
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	Accumulate_one_IRCost            = uint64(211)
	Normalize_one_IRCost             = uint64(48)
	Archtime_accumulate_block_IRCost = uint64(10)
	Archtime_normalize_range_IRCost  = uint64(73)
	Archtime_normalize_block_IRCost  = uint64(16)
	Archtime_normals_begin_IRCost    = uint64(62)
	Archtime_normals_step_IRCost     = uint64(133)
)
