// SPDX-License-Identifier: Apache-2.0 OR MIT
// Code generated by cue export from spec/normals.cue; DO NOT EDIT.

package geometry

const (
	QuotaAdmission      = uint64(24)
	QuotaBindingGuard   = uint64(12)
	QuotaTransition     = uint64(4)
	QuotaZeroUnit       = uint64(3)
	QuotaAccumOne       = uint64(211)
	QuotaAccumBlock     = uint64(10)
	QuotaAccumFallback4 = uint64(844)
	QuotaAccumCharge4   = uint64(844)
	QuotaNormOne        = uint64(48)
	QuotaNormBlock      = uint64(134)
	QuotaNormFallback4  = uint64(192)
	QuotaNormCharge4    = uint64(192)
	QuotaBeginPos       = uint64(1)
	QuotaBeginIdx       = uint64(1)
	QuotaLastStore      = uint64(4)
)
