// SPDX-License-Identifier: Apache-2.0 OR MIT
// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=dfca98dacd7c75600b1f60e2bb705e019e62dc5885748420f75c942691777351
package geometry

import "math"

func Archtime_small_bounds(positions []float32, nfloats uint64, out []float64) {
	var v3 uint64
	var v4 float64
	var v5 float64
	var v6 float64
	var v7 float64
	var v8 float64
	var v9 float64
	var v26 float64
	var v30 float64
	var v34 float64
	v4 = float64(positions[0])
	v5 = float64(positions[1])
	v6 = float64(positions[2])
	v7 = v4
	v8 = v5
	v9 = v6
	for v3 = 3; v3 < nfloats; v3 += 3 {
		v26 = float64(positions[v3])
		v30 = float64(positions[v3+1])
		v34 = float64(positions[v3+2])
		if v26 < v4 {
			v4 = v26
		}
		if v30 < v5 {
			v5 = v30
		}
		if v34 < v6 {
			v6 = v34
		}
		if v26 > v7 {
			v7 = v26
		}
		if v30 > v8 {
			v8 = v30
		}
		if v34 > v9 {
			v9 = v34
		}
	}
	out[0] = v4
	out[1] = v5
	out[2] = v6
	out[3] = v7
	out[4] = v8
	out[5] = v9
}

func Archtime_small_sphere(positions []float32, nfloats uint64, out []float64) {
	var v4 uint64
	var v12 float64
	var v20 float64
	var v27 float64
	var v34 float64
	var v41 float64
	var v46 float64
	var v51 float64
	var v60 float64
	var v3 [6]float64
	Archtime_small_bounds(positions, nfloats, v3[:])
	v20 = (v3[0] + v3[3]) * float64(0.5)
	v27 = (v3[1] + v3[4]) * float64(0.5)
	v34 = (v3[2] + v3[5]) * float64(0.5)
	v12 = float64(0)
	for v4 = 0; v4 < nfloats; v4 += 3 {
		v41 = float64(positions[v4]) - v20
		v46 = float64(positions[v4+1]) - v27
		v51 = float64(positions[v4+2]) - v34
		v60 = float64(float64(v41*v41)+float64(v46*v46)) + float64(v51*v51)
		if v60 > v12 {
			v12 = v60
		}
	}
	out[0] = v20
	out[1] = v27
	out[2] = v34
	out[3] = math.Sqrt(v12)
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	Archtime_small_bounds_IRCost = uint64(61)
	Archtime_small_sphere_IRCost = uint64(78)
)
