// SPDX-License-Identifier: Apache-2.0 OR MIT
// Code generated by sgoiter emit go127; DO NOT EDIT.
// sgoiter-stamp: sha256=4aa32b41c620a4b24af9f4774532747b269e7cdd985fdbc75c412293a1eeed6e
package c2strclass

var KUtf8Hi = [16]byte{0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 3, 4}

func C2strclass_is_latin1_u16(in []uint16, n uint64) byte {
	var v2 byte
	var v4 uint64
	if uint64(len(in)) < n {
		n = uint64(len(in))
	}
	v2 = 1
	for v4 = 0; v4 < n; v4++ {
		v15 := func() byte {
			if byte(uint16(in[v4]>>8)) != 0 {
				return 1
			}
			return 0
		}()
		v2 &= byte(uint32(1) - uint32(v15))
	}
	return v2
}

func C2strclass_utf8_classify(in []byte, n uint64, out []byte) {
	var v4 uint64
	for v4 = 0; v4 < n; v4++ {
		v9 := in[v4]
		v16 := func() uint64 {
			if v9 >= 0xf5 {
				return 1
			}
			return 0
		}()
		out[v4] = KUtf8Hi[int(uint64(uint64(v9)>>4))] + byte(v16)
	}
}

func C2strclass_ascii_upper(buf []byte, n uint64) {
	var v2 uint64
	if uint64(len(buf)) < n {
		n = uint64(len(buf))
	}
	for v2 = 0; v2 < n; v2++ {
		v7 := buf[v2]
		v15 := func() uint64 {
			if (v7 - 'a') <= 25 {
				return 1
			}
			return 0
		}()
		buf[v2] = v7 - (byte(v15) * 32)
	}
}

func C2strclass_lex_class(in []byte, n uint64, out []byte) {
	var v3 uint64
	for v3 = 0; v3 < n; v3++ {
		v8 := in[v3]
		v15 := func() uint64 {
			if (v8 - 'A') <= 25 {
				return 1
			}
			return 0
		}()
		v23 := func() uint64 {
			if (v8 - 'a') <= 25 {
				return 1
			}
			return 0
		}()
		v28 := func() uint64 {
			if v8 == '_' {
				return 1
			}
			return 0
		}()
		v33 := func() uint64 {
			if v8 == 36 {
				return 1
			}
			return 0
		}()
		v41 := func() uint64 {
			if (v8 - '0') <= 9 {
				return 1
			}
			return 0
		}()
		v42 := byte(v41)
		v46 := ((byte(v15) | byte(v23)) | byte(v28)) | byte(v33)
		v54 := func() uint64 {
			if v8 == 32 {
				return 1
			}
			return 0
		}()
		v59 := func() uint64 {
			if v8 == 9 {
				return 1
			}
			return 0
		}()
		v64 := func() uint64 {
			if v8 == 11 {
				return 1
			}
			return 0
		}()
		v69 := func() uint64 {
			if v8 == 12 {
				return 1
			}
			return 0
		}()
		v79 := func() uint64 {
			if v8 == 10 {
				return 1
			}
			return 0
		}()
		v84 := func() uint64 {
			if v8 == 13 {
				return 1
			}
			return 0
		}()
		v91 := func() uint64 {
			if v8 >= 0x80 {
				return 1
			}
			return 0
		}()
		out[v3] = ((((v46 | ((v46 | v42) * 2)) | (v42 * 4)) | ((((byte(v54) | byte(v59)) | byte(v64)) | byte(v69)) * 8)) | ((byte(v79) | byte(v84)) * 16)) | (byte(v91) * 32)
	}
}

// IRCosts counted from IR opcodes via rodata.IROpCost; not a kernel-name table.
const (
	C2strclass_is_latin1_u16_IRCost = uint64(25)
	C2strclass_utf8_classify_IRCost = uint64(20)
	C2strclass_ascii_upper_IRCost   = uint64(23)
	C2strclass_lex_class_IRCost     = uint64(111)
)
